package org.crowdcache.rpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crowdrpcProto.proto

public final class CrowdRPCProto {
  private CrowdRPCProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CrowdMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CrowdMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .CrowdMsg.MsgType msgType = 1;</code>
     */
    boolean hasMsgType();
    /**
     * <code>required .CrowdMsg.MsgType msgType = 1;</code>
     */
    CrowdMsg.MsgType getMsgType();

    /**
     * <code>required uint32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 2;</code>
     */
    int getId();

    /**
     * <code>optional .GetEventsReq getEventsReq = 3;</code>
     */
    boolean hasGetEventsReq();
    /**
     * <code>optional .GetEventsReq getEventsReq = 3;</code>
     */
    GetEventsReq getGetEventsReq();
    /**
     * <code>optional .GetEventsReq getEventsReq = 3;</code>
     */
    GetEventsReqOrBuilder getGetEventsReqOrBuilder();

    /**
     * <code>optional .GetEventsResp getEventsResp = 4;</code>
     */
    boolean hasGetEventsResp();
    /**
     * <code>optional .GetEventsResp getEventsResp = 4;</code>
     */
    GetEventsResp getGetEventsResp();
    /**
     * <code>optional .GetEventsResp getEventsResp = 4;</code>
     */
    GetEventsRespOrBuilder getGetEventsRespOrBuilder();
  }
  /**
   * Protobuf type {@code CrowdMsg}
   */
  public  static final class CrowdMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CrowdMsg)
      CrowdMsgOrBuilder {
    // Use CrowdMsg.newBuilder() to construct.
    private CrowdMsg(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private CrowdMsg() {
      msgType_ = 0;
      id_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CrowdMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              MsgType value = MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgType_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readUInt32();
              break;
            }
            case 26: {
              GetEventsReq.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = getEventsReq_.toBuilder();
              }
              getEventsReq_ = input.readMessage(GetEventsReq.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(getEventsReq_);
                getEventsReq_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              GetEventsResp.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = getEventsResp_.toBuilder();
              }
              getEventsResp_ = input.readMessage(GetEventsResp.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(getEventsResp_);
                getEventsResp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CrowdRPCProto.internal_static_CrowdMsg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CrowdRPCProto.internal_static_CrowdMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CrowdMsg.class, Builder.class);
    }

    /**
     * Protobuf enum {@code CrowdMsg.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GET_EVENTS = 0;</code>
       */
      GET_EVENTS(0, 0),
      /**
       * <code>GET_EVENTS_RESP = 1;</code>
       */
      GET_EVENTS_RESP(1, 1),
      ;

      /**
       * <code>GET_EVENTS = 0;</code>
       */
      public static final int GET_EVENTS_VALUE = 0;
      /**
       * <code>GET_EVENTS_RESP = 1;</code>
       */
      public static final int GET_EVENTS_RESP_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      public static MsgType valueOf(int value) {
        switch (value) {
          case 0: return GET_EVENTS;
          case 1: return GET_EVENTS_RESP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return CrowdMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CrowdMsg.MsgType)
    }

    private int bitField0_;
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <code>required .CrowdMsg.MsgType msgType = 1;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .CrowdMsg.MsgType msgType = 1;</code>
     */
    public MsgType getMsgType() {
      MsgType result = MsgType.valueOf(msgType_);
      return result == null ? MsgType.GET_EVENTS : result;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required uint32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int GETEVENTSREQ_FIELD_NUMBER = 3;
    private GetEventsReq getEventsReq_;
    /**
     * <code>optional .GetEventsReq getEventsReq = 3;</code>
     */
    public boolean hasGetEventsReq() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .GetEventsReq getEventsReq = 3;</code>
     */
    public GetEventsReq getGetEventsReq() {
      return getEventsReq_ == null ? GetEventsReq.getDefaultInstance() : getEventsReq_;
    }
    /**
     * <code>optional .GetEventsReq getEventsReq = 3;</code>
     */
    public GetEventsReqOrBuilder getGetEventsReqOrBuilder() {
      return getEventsReq_ == null ? GetEventsReq.getDefaultInstance() : getEventsReq_;
    }

    public static final int GETEVENTSRESP_FIELD_NUMBER = 4;
    private GetEventsResp getEventsResp_;
    /**
     * <code>optional .GetEventsResp getEventsResp = 4;</code>
     */
    public boolean hasGetEventsResp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .GetEventsResp getEventsResp = 4;</code>
     */
    public GetEventsResp getGetEventsResp() {
      return getEventsResp_ == null ? GetEventsResp.getDefaultInstance() : getEventsResp_;
    }
    /**
     * <code>optional .GetEventsResp getEventsResp = 4;</code>
     */
    public GetEventsRespOrBuilder getGetEventsRespOrBuilder() {
      return getEventsResp_ == null ? GetEventsResp.getDefaultInstance() : getEventsResp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasGetEventsReq()) {
        if (!getGetEventsReq().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getGetEventsReq());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, getGetEventsResp());
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getGetEventsReq());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getGetEventsResp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static CrowdMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CrowdMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CrowdMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CrowdMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CrowdMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CrowdMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CrowdMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CrowdMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CrowdMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CrowdMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CrowdMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CrowdMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CrowdMsg)
        CrowdMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CrowdRPCProto.internal_static_CrowdMsg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CrowdRPCProto.internal_static_CrowdMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CrowdMsg.class, Builder.class);
      }

      // Construct using CrowdRPCProto.CrowdMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGetEventsReqFieldBuilder();
          getGetEventsRespFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (getEventsReqBuilder_ == null) {
          getEventsReq_ = null;
        } else {
          getEventsReqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (getEventsRespBuilder_ == null) {
          getEventsResp_ = null;
        } else {
          getEventsRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CrowdRPCProto.internal_static_CrowdMsg_descriptor;
      }

      public CrowdMsg getDefaultInstanceForType() {
        return CrowdMsg.getDefaultInstance();
      }

      public CrowdMsg build() {
        CrowdMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CrowdMsg buildPartial() {
        CrowdMsg result = new CrowdMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (getEventsReqBuilder_ == null) {
          result.getEventsReq_ = getEventsReq_;
        } else {
          result.getEventsReq_ = getEventsReqBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (getEventsRespBuilder_ == null) {
          result.getEventsResp_ = getEventsResp_;
        } else {
          result.getEventsResp_ = getEventsRespBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CrowdMsg) {
          return mergeFrom((CrowdMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CrowdMsg other) {
        if (other == CrowdMsg.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasGetEventsReq()) {
          mergeGetEventsReq(other.getGetEventsReq());
        }
        if (other.hasGetEventsResp()) {
          mergeGetEventsResp(other.getGetEventsResp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgType()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        if (hasGetEventsReq()) {
          if (!getGetEventsReq().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CrowdMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CrowdMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgType_ = 0;
      /**
       * <code>required .CrowdMsg.MsgType msgType = 1;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .CrowdMsg.MsgType msgType = 1;</code>
       */
      public MsgType getMsgType() {
        MsgType result = MsgType.valueOf(msgType_);
        return result == null ? MsgType.GET_EVENTS : result;
      }
      /**
       * <code>required .CrowdMsg.MsgType msgType = 1;</code>
       */
      public Builder setMsgType(MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .CrowdMsg.MsgType msgType = 1;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required uint32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private GetEventsReq getEventsReq_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          GetEventsReq, GetEventsReq.Builder, GetEventsReqOrBuilder> getEventsReqBuilder_;
      /**
       * <code>optional .GetEventsReq getEventsReq = 3;</code>
       */
      public boolean hasGetEventsReq() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .GetEventsReq getEventsReq = 3;</code>
       */
      public GetEventsReq getGetEventsReq() {
        if (getEventsReqBuilder_ == null) {
          return getEventsReq_ == null ? GetEventsReq.getDefaultInstance() : getEventsReq_;
        } else {
          return getEventsReqBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .GetEventsReq getEventsReq = 3;</code>
       */
      public Builder setGetEventsReq(GetEventsReq value) {
        if (getEventsReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          getEventsReq_ = value;
          onChanged();
        } else {
          getEventsReqBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .GetEventsReq getEventsReq = 3;</code>
       */
      public Builder setGetEventsReq(
          GetEventsReq.Builder builderForValue) {
        if (getEventsReqBuilder_ == null) {
          getEventsReq_ = builderForValue.build();
          onChanged();
        } else {
          getEventsReqBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .GetEventsReq getEventsReq = 3;</code>
       */
      public Builder mergeGetEventsReq(GetEventsReq value) {
        if (getEventsReqBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              getEventsReq_ != null &&
              getEventsReq_ != GetEventsReq.getDefaultInstance()) {
            getEventsReq_ =
              GetEventsReq.newBuilder(getEventsReq_).mergeFrom(value).buildPartial();
          } else {
            getEventsReq_ = value;
          }
          onChanged();
        } else {
          getEventsReqBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .GetEventsReq getEventsReq = 3;</code>
       */
      public Builder clearGetEventsReq() {
        if (getEventsReqBuilder_ == null) {
          getEventsReq_ = null;
          onChanged();
        } else {
          getEventsReqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .GetEventsReq getEventsReq = 3;</code>
       */
      public GetEventsReq.Builder getGetEventsReqBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getGetEventsReqFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .GetEventsReq getEventsReq = 3;</code>
       */
      public GetEventsReqOrBuilder getGetEventsReqOrBuilder() {
        if (getEventsReqBuilder_ != null) {
          return getEventsReqBuilder_.getMessageOrBuilder();
        } else {
          return getEventsReq_ == null ?
              GetEventsReq.getDefaultInstance() : getEventsReq_;
        }
      }
      /**
       * <code>optional .GetEventsReq getEventsReq = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          GetEventsReq, GetEventsReq.Builder, GetEventsReqOrBuilder>
          getGetEventsReqFieldBuilder() {
        if (getEventsReqBuilder_ == null) {
          getEventsReqBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              GetEventsReq, GetEventsReq.Builder, GetEventsReqOrBuilder>(
                  getGetEventsReq(),
                  getParentForChildren(),
                  isClean());
          getEventsReq_ = null;
        }
        return getEventsReqBuilder_;
      }

      private GetEventsResp getEventsResp_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          GetEventsResp, GetEventsResp.Builder, GetEventsRespOrBuilder> getEventsRespBuilder_;
      /**
       * <code>optional .GetEventsResp getEventsResp = 4;</code>
       */
      public boolean hasGetEventsResp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .GetEventsResp getEventsResp = 4;</code>
       */
      public GetEventsResp getGetEventsResp() {
        if (getEventsRespBuilder_ == null) {
          return getEventsResp_ == null ? GetEventsResp.getDefaultInstance() : getEventsResp_;
        } else {
          return getEventsRespBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .GetEventsResp getEventsResp = 4;</code>
       */
      public Builder setGetEventsResp(GetEventsResp value) {
        if (getEventsRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          getEventsResp_ = value;
          onChanged();
        } else {
          getEventsRespBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .GetEventsResp getEventsResp = 4;</code>
       */
      public Builder setGetEventsResp(
          GetEventsResp.Builder builderForValue) {
        if (getEventsRespBuilder_ == null) {
          getEventsResp_ = builderForValue.build();
          onChanged();
        } else {
          getEventsRespBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .GetEventsResp getEventsResp = 4;</code>
       */
      public Builder mergeGetEventsResp(GetEventsResp value) {
        if (getEventsRespBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              getEventsResp_ != null &&
              getEventsResp_ != GetEventsResp.getDefaultInstance()) {
            getEventsResp_ =
              GetEventsResp.newBuilder(getEventsResp_).mergeFrom(value).buildPartial();
          } else {
            getEventsResp_ = value;
          }
          onChanged();
        } else {
          getEventsRespBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .GetEventsResp getEventsResp = 4;</code>
       */
      public Builder clearGetEventsResp() {
        if (getEventsRespBuilder_ == null) {
          getEventsResp_ = null;
          onChanged();
        } else {
          getEventsRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .GetEventsResp getEventsResp = 4;</code>
       */
      public GetEventsResp.Builder getGetEventsRespBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getGetEventsRespFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .GetEventsResp getEventsResp = 4;</code>
       */
      public GetEventsRespOrBuilder getGetEventsRespOrBuilder() {
        if (getEventsRespBuilder_ != null) {
          return getEventsRespBuilder_.getMessageOrBuilder();
        } else {
          return getEventsResp_ == null ?
              GetEventsResp.getDefaultInstance() : getEventsResp_;
        }
      }
      /**
       * <code>optional .GetEventsResp getEventsResp = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          GetEventsResp, GetEventsResp.Builder, GetEventsRespOrBuilder>
          getGetEventsRespFieldBuilder() {
        if (getEventsRespBuilder_ == null) {
          getEventsRespBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              GetEventsResp, GetEventsResp.Builder, GetEventsRespOrBuilder>(
                  getGetEventsResp(),
                  getParentForChildren(),
                  isClean());
          getEventsResp_ = null;
        }
        return getEventsRespBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:CrowdMsg)
    }

    // @@protoc_insertion_point(class_scope:CrowdMsg)
    private static final CrowdMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CrowdMsg();
    }

    public static CrowdMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<CrowdMsg> PARSER =
        new com.google.protobuf.AbstractParser<CrowdMsg>() {
      public CrowdMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new CrowdMsg(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @Override
    public com.google.protobuf.Parser<CrowdMsg> getParserForType() {
      return PARSER;
    }

    public CrowdMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetEventsReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetEventsReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 startTime = 1;</code>
     */
    boolean hasStartTime();
    /**
     * <code>required uint64 startTime = 1;</code>
     */
    long getStartTime();

    /**
     * <code>required uint64 endTime = 2;</code>
     */
    boolean hasEndTime();
    /**
     * <code>required uint64 endTime = 2;</code>
     */
    long getEndTime();
  }
  /**
   * Protobuf type {@code GetEventsReq}
   */
  public  static final class GetEventsReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GetEventsReq)
      GetEventsReqOrBuilder {
    // Use GetEventsReq.newBuilder() to construct.
    private GetEventsReq(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private GetEventsReq() {
      startTime_ = 0L;
      endTime_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetEventsReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              startTime_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              endTime_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CrowdRPCProto.internal_static_GetEventsReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CrowdRPCProto.internal_static_GetEventsReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetEventsReq.class, Builder.class);
    }

    private int bitField0_;
    public static final int STARTTIME_FIELD_NUMBER = 1;
    private long startTime_;
    /**
     * <code>required uint64 startTime = 1;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 startTime = 1;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 2;
    private long endTime_;
    /**
     * <code>required uint64 endTime = 2;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 endTime = 2;</code>
     */
    public long getEndTime() {
      return endTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, startTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, endTime_);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, startTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, endTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static GetEventsReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetEventsReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetEventsReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetEventsReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetEventsReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GetEventsReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static GetEventsReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static GetEventsReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static GetEventsReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GetEventsReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetEventsReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetEventsReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetEventsReq)
        GetEventsReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CrowdRPCProto.internal_static_GetEventsReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CrowdRPCProto.internal_static_GetEventsReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetEventsReq.class, Builder.class);
      }

      // Construct using CrowdRPCProto.GetEventsReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        startTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CrowdRPCProto.internal_static_GetEventsReq_descriptor;
      }

      public GetEventsReq getDefaultInstanceForType() {
        return GetEventsReq.getDefaultInstance();
      }

      public GetEventsReq build() {
        GetEventsReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GetEventsReq buildPartial() {
        GetEventsReq result = new GetEventsReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.endTime_ = endTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetEventsReq) {
          return mergeFrom((GetEventsReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetEventsReq other) {
        if (other == GetEventsReq.getDefaultInstance()) return this;
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStartTime()) {
          return false;
        }
        if (!hasEndTime()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetEventsReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetEventsReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long startTime_ ;
      /**
       * <code>required uint64 startTime = 1;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 startTime = 1;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>required uint64 startTime = 1;</code>
       */
      public Builder setStartTime(long value) {
        bitField0_ |= 0x00000001;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 startTime = 1;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <code>required uint64 endTime = 2;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 endTime = 2;</code>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>required uint64 endTime = 2;</code>
       */
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000002;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 endTime = 2;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        endTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetEventsReq)
    }

    // @@protoc_insertion_point(class_scope:GetEventsReq)
    private static final GetEventsReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetEventsReq();
    }

    public static GetEventsReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<GetEventsReq> PARSER =
        new com.google.protobuf.AbstractParser<GetEventsReq>() {
      public GetEventsReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GetEventsReq(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @Override
    public com.google.protobuf.Parser<GetEventsReq> getParserForType() {
      return PARSER;
    }

    public GetEventsReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetEventsRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetEventsResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated uint32 events = 1;</code>
     */
    java.util.List<Integer> getEventsList();
    /**
     * <code>repeated uint32 events = 1;</code>
     */
    int getEventsCount();
    /**
     * <code>repeated uint32 events = 1;</code>
     */
    int getEvents(int index);
  }
  /**
   * Protobuf type {@code GetEventsResp}
   */
  public  static final class GetEventsResp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GetEventsResp)
      GetEventsRespOrBuilder {
    // Use GetEventsResp.newBuilder() to construct.
    private GetEventsResp(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private GetEventsResp() {
      events_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetEventsResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                events_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              events_.add(input.readUInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                events_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                events_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          events_ = java.util.Collections.unmodifiableList(events_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CrowdRPCProto.internal_static_GetEventsResp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CrowdRPCProto.internal_static_GetEventsResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetEventsResp.class, Builder.class);
    }

    public static final int EVENTS_FIELD_NUMBER = 1;
    private java.util.List<Integer> events_;
    /**
     * <code>repeated uint32 events = 1;</code>
     */
    public java.util.List<Integer>
        getEventsList() {
      return events_;
    }
    /**
     * <code>repeated uint32 events = 1;</code>
     */
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated uint32 events = 1;</code>
     */
    public int getEvents(int index) {
      return events_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < events_.size(); i++) {
        output.writeUInt32(1, events_.get(i));
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < events_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(events_.get(i));
        }
        size += dataSize;
        size += 1 * getEventsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static GetEventsResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetEventsResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetEventsResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetEventsResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetEventsResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GetEventsResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static GetEventsResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static GetEventsResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static GetEventsResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GetEventsResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetEventsResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetEventsResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetEventsResp)
        GetEventsRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CrowdRPCProto.internal_static_GetEventsResp_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CrowdRPCProto.internal_static_GetEventsResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetEventsResp.class, Builder.class);
      }

      // Construct using CrowdRPCProto.GetEventsResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        events_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CrowdRPCProto.internal_static_GetEventsResp_descriptor;
      }

      public GetEventsResp getDefaultInstanceForType() {
        return GetEventsResp.getDefaultInstance();
      }

      public GetEventsResp build() {
        GetEventsResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GetEventsResp buildPartial() {
        GetEventsResp result = new GetEventsResp(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          events_ = java.util.Collections.unmodifiableList(events_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.events_ = events_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetEventsResp) {
          return mergeFrom((GetEventsResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetEventsResp other) {
        if (other == GetEventsResp.getDefaultInstance()) return this;
        if (!other.events_.isEmpty()) {
          if (events_.isEmpty()) {
            events_ = other.events_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEventsIsMutable();
            events_.addAll(other.events_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetEventsResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetEventsResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Integer> events_ = java.util.Collections.emptyList();
      private void ensureEventsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          events_ = new java.util.ArrayList<Integer>(events_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint32 events = 1;</code>
       */
      public java.util.List<Integer>
          getEventsList() {
        return java.util.Collections.unmodifiableList(events_);
      }
      /**
       * <code>repeated uint32 events = 1;</code>
       */
      public int getEventsCount() {
        return events_.size();
      }
      /**
       * <code>repeated uint32 events = 1;</code>
       */
      public int getEvents(int index) {
        return events_.get(index);
      }
      /**
       * <code>repeated uint32 events = 1;</code>
       */
      public Builder setEvents(
          int index, int value) {
        ensureEventsIsMutable();
        events_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 events = 1;</code>
       */
      public Builder addEvents(int value) {
        ensureEventsIsMutable();
        events_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 events = 1;</code>
       */
      public Builder addAllEvents(
          Iterable<? extends Integer> values) {
        ensureEventsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, events_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 events = 1;</code>
       */
      public Builder clearEvents() {
        events_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetEventsResp)
    }

    // @@protoc_insertion_point(class_scope:GetEventsResp)
    private static final GetEventsResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetEventsResp();
    }

    public static GetEventsResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<GetEventsResp> PARSER =
        new com.google.protobuf.AbstractParser<GetEventsResp>() {
      public GetEventsResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GetEventsResp(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @Override
    public com.google.protobuf.Parser<GetEventsResp> getParserForType() {
      return PARSER;
    }

    public GetEventsResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CrowdMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CrowdMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetEventsReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetEventsReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetEventsResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetEventsResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023crowdrpcProto.proto\"\266\001\n\010CrowdMsg\022\"\n\007ms" +
      "gType\030\001 \002(\0162\021.CrowdMsg.MsgType\022\n\n\002id\030\002 \002" +
      "(\r\022#\n\014getEventsReq\030\003 \001(\0132\r.GetEventsReq\022" +
      "%\n\rgetEventsResp\030\004 \001(\0132\016.GetEventsResp\"." +
      "\n\007MsgType\022\016\n\nGET_EVENTS\020\000\022\023\n\017GET_EVENTS_" +
      "RESP\020\001\"2\n\014GetEventsReq\022\021\n\tstartTime\030\001 \002(" +
      "\004\022\017\n\007endTime\030\002 \002(\004\"\037\n\rGetEventsResp\022\016\n\006e" +
      "vents\030\001 \003(\rB\017B\rCrowdRPCProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CrowdMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CrowdMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CrowdMsg_descriptor,
        new String[] { "MsgType", "Id", "GetEventsReq", "GetEventsResp", });
    internal_static_GetEventsReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetEventsReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetEventsReq_descriptor,
        new String[] { "StartTime", "EndTime", });
    internal_static_GetEventsResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetEventsResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetEventsResp_descriptor,
        new String[] { "Events", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
